### ISSUE TITLE
Can you provide the database?

### ISSUE THREAD

**Issue by jt14den** [datacarpentry/sql-socialsci#1]
@PeterSmyth12 I'm teaching databases and SQL at UCLA to social scientists and would like to use some of this material. However, I can't find the database. Can you point me to it?

**Comment by ErinBecker** [comment]
Hi @jt14den - this material is in active development and not quite ready for teaching yet. We're just wrapping up the initial writing phase and haven't had a chance to do a comprehensive read through yet, so there are likely to be typos/broken links/missing info. I wouldn't recommend using them for a live course. We're planning some pilot workshops in the next few months and a release of these materials in the first quarter of next year.

**Comment by marwahaha** [comment]
I recommend closing this ticket -- it is available at 
https://datacarpentry.org/sql-socialsci/data/SQL_SAFI.sqlite
