### ISSUE TITLE
Update the outdated URL in the contributing.md

### ISSUE THREAD

**Issue by AddiMT** [datacarpentry/sql-socialsci#40]
The link about how to contribute to github https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github in controubuting.md (https://github.com/datacarpentry/sql-socialsci/blob/8346657ce297c433bebe2bde8d5cf88272f79626/CONTRIBUTING.md) now returns a 404 and does not work. The link needs to be updated to this new location: https://app.egghead.io/playlists/how-to-contribute-to-an-open-source-project-on-github

---

**Comment by tobyhodges** [comment]
closed by #41
